### ISSUE TITLE
securitySchemes is being cleared

### ISSUE THREAD

**Issue by pisaychuk** [dolmen-go/openapi-preprocessor#10]
Hey @dolmen, I noticed an issue with my doc after running preprocessing. I have the following config in yml:

```
security:
  - httpBasic: []
....
components:
  securitySchemes:
    httpBasic:
      type: http
      scheme: basic
```

Once I run the preprocessing, the resulting json is 

```

"components" : {
   ....
    "securitySchemes" : { }
}

"security" : [ {
    "httpBasic" : [ ]
  } ],

```
As you see securitySchemes is being cleared.
